### ISSUE TITLE
How to add a failing test?

### ISSUE THREAD

**Issue by JayBazuzi** [RefactoringCombos/ArlosCommitNotation#27]
Typically in my red/green/refactor cycle I'll write a test, see it fail, make it pass, and then commit with `F` or `F!!` or `B` or `B!!`. If I have named my new test well, it will be the commit title.

Sometimes I want to make it obvious that I wrote a failing test _before_ making it pass, so I want to commit the new test by itself.

I wonder if `T**` would be a good prefix for this situation? Maybe `f  ` / `b  ` would be a good followup to a `T**`?

**Comment by arlobelshee** [comment]
Yes, I would use T** for the failing test. I would still use F or B for the
following change. Lower case would imply that I had evidence the change had
no effect on untested behavior. I still know of no way to get that level of
safety guarantee when changing behavior (F or B).

Arlo Belshee
Principal Technical and Leadership Agile Coach
***@***.***
http://digdeeproots.com/
@arlobelshee   in:arlobelshee

**Comment by JayBazuzi** [comment]
I've been playing around with this recently. In one case I found that code formatting wasn't getting validated in CI, which had allowed formatting to diverge from the norm.

- First commit was `E** Add formatting validation to CI`
- Second commit was `a   format with ktlint`

And now everything is green and passing.

Then thought about what to call the pull request. The "union of all risks" would be `E**`, but there's no risk to the product so I want to use `e   `.

**Comment by arlobelshee** [comment]
Aye. I've notice similarly with PR commits and **. When working on
infrastructure, I often have at least one ** commit in a chain - because I
really have to commit in order to test it. Yet once we get to the final,
the risk has been reduced by running those tests. So I've been ending up
with a bunch of E - foo that include at least one E**, and even some ***
commits.

I'm pretty sure that a universal rule won't work here. So I think I'd leave
the rule as is - use the union of risk - but when training people I'd ask
them to think about risk and decide if anything has reduced it below that
number by addressing every single ** in the sequence.

Arlo Belshee
***@***.***
http://arlobelshee.com/
@arlobelshee <https://twitter.com/arlobelshee>   in:arlobelshee

**Comment by JayBazuzi** [comment]
> think about risk and decide if anything has reduced it

I like this.
